### ISSUE TITLE
[feat] apply optimistic update to scrap data

### ISSUE THREAD

**Issue by godhyzzang** [Kernel360/F2-BIENGUAL-FE#189]
## 이슈 설명

> optimisitc update를 scrap에도 적용합니다. 

## 작업 상세 내용

- [ ] TODO
- [ ] TODO
- [ ] TODO

## 참고 자료 (선택)

> 관련 문서나 링크가 있다면 첨부해주세요

**Comment by smosco** [comment]
스크랩 쪽 제가 해보겠습니다~
