### ISSUE TITLE
[feat] add focus button to listening script component

### ISSUE THREAD

**Issue by godhyzzang** [Kernel360/F2-BIENGUAL-FE#325]
## 이슈 설명

> focus버튼 추가

## 작업 상세 내용
- [ ] isFocus로 받도록 오픈소스 수정하기 
- [ ] 음소거 버튼 만들기
- [ ] 반응형 줄였을 때 겹치는 문제 해결하기
- [ ] throttling은 외부로 빼기..?
- [ ] 버튼을 외부로 뺄 수 있는지?

## 참고 자료 (선택)

> 관련 문서나 링크가 있다면 첨부해주세요

**Comment by lkilu6456546** [comment]
Hello, I tried to solve the issue.

This is what I did:

Added a focus button to ListeningDetailClient and ReadingDetailClient components. The button toggles a focus mode that hides other elements on the page.

You can review changes in this commit: https://github.com/lkilu6456546/Kernel360-F2-BIENGUAL-FE-325/commit/1c57b8316545a6d8ac6bef02f536d8c12bdb9e45.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
